name: Build client

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'
  workflow_dispatch:

concurrency:
  group: build-push-${{ github.ref_type }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build ${{ matrix.title }} image
    strategy:
      matrix:
        include:
          -
            title: Debian
            tag: "5.4.0-nginx1.27.2"
          -
            title: Alpine
            tag: "5.4.0-nginx1.27.2-alpine"
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          #push: ${{ github.ref_type == 'tag' && 'true' || 'false' }}
          push: true
          platforms: linux/386,linux/amd64,linux/arm/v7,linux/arm64
          build-args: |
            DOCKER_NGINX_CERTBOT_TAG=${{ matrix.tag }}
          tags: |
            ghcr.io/${{ github.actor }}/nginx-certbot-jinja:latest
